# -*- coding: utf-8 -*-
"""height_analyzer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTWOswpDo0TCg9017EyfgzskwcUqtQrs
"""

import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from google.colab import files 
uploaded = files.upload()


raw = pd.read_csv('main.csv')

#too much data. Data is filtered to only include 18 yr old boys 
temp = []
for x in range(raw.shape[0]):
   if raw.iloc[x,3] == 18: 
     if raw.iloc[x,1] == 'Boys': 
      temp.append(x)

main = raw.take(temp)
print(raw.info())
print(main.info())


#drops null values 
main = main.dropna()

countries = []

#input for number of countries to compare 
invalidinput = True  
while invalidinput == True: 
  invalidinput = False
  number = input('How many countries do you want to compare? ')
  try: 
    int(number)
  except ValueError: 
    print('Please enter a number. ') 
    invalidinput = True

number = int(number) 
 
#input for each country 
for x in range(number): 
  invalidinput = True
  while invalidinput == True: 
    invalidinput = False 
    countryinput = input('Enter a country: ')
    countryinput = countryinput.title()
    if countryinput == 'Usa': 
      countryinput = 'United States of America' 
    if countryinput == 'Us': 
      countryinput = 'United States of America' 
    if countryinput == 'Uk': 
      countryinput = 'United Kingdom' 
    if countryinput == 'Korea': 
      countryinput = 'South Korea' 
    
    if any(countryinput for x in main['Country'].unique()): 
      invalidinput = False

    else: 
      invalidinput = True 
    countries.append(countryinput) 
  
print(countries)


#sorting data appropriately into input 
countrysorted = [[] for x in range(len(countries))]

cdict = {}

for x in range(len(countries)): 
  cdict[countries[x]] = []

yeardict = {}

for x in range(len(countries)): 
  yeardict[countries[x]] = []


for x in range(len(countries)): 
  for y in range(main.shape[0]): 
    if main.iloc[y,0] == countries[x]: 
      cdict[countries[x]].append(main.iloc[y,4])
      yeardict[countries[x]].append(main.iloc[y,2])


heights = [[] for x in range(len(countries))]
years = [[] for x in range(len(countries))]


for x, y in zip(range(len(countries)), cdict):
  heights[x] = np.append(heights[x], cdict[y])
  years[x] = np.append(years[x], yeardict[y]) 


countries, cheights, cyears = cdict.keys(), cdict.values(), yeardict.values()


#plot boxplot to compare between countries 
boxplot = plt.boxplot(cheights)
plt.xticks([*range(1,len(countries)+1)], countries)
plt.xlabel('Countries', weight = 'bold')
plt.ylabel('Height (cm)', weight = 'bold')
plt.xticks(rotation=45)
plt.show()

#plot lineplot to show changes in height over the years  
lineplot = plt.plot()
for x in range(len(countries)): 
  plt.plot(years[x], heights[x])

plt.legend(countries)
plt.xlabel('Countries', weight = 'bold')
plt.ylabel('Height (cm)', weight = 'bold') 
plt.xticks(rotation=45)
plt.show()